### ISSUE TITLE
Metal support

### ISSUE THREAD

**Issue by JoelOtter** [amzeratul/halley#29]
Hi @amzeratul & contributors,

I'd like to look into building a MVP for Metal support (eventually leading to iOS) in Halley. I think this would help me learn the engine's ins and outs better, and also would future proof the engine on Mac and iOS if Apple ultimately decides to pull the OpenGL rug out.

Unfortunately, Metal does not have a C/C++ API - the only options are Objective-C or Swift. This would add an additional language to your codebase, something I imagine you're hesitant to get behind for reasons that are very understandable.

I'd be interested to know your thoughts on what the optimal layout for this kind of thing looks like. I imagine I'd take something similar to the approach of (sadly not really maintained) [mtlpp](https://github.com/naleksiev/mtlpp), which provides Objective-C-free headers, meaning compilation will still work on platforms without Metal support, even if linking doesn't.

Really liking the look of this engine so far, and congrats on the successful launch of Wargroove.

Cheers
Joel

**Comment by amzeratul** [comment]
Hi!

Sorry about the slow response, it's been a busy time following the launch of Wargroove. :)

Halley is designed so only some sub-projects are compiled at any given platform. For example, halley-dx11 will only build on Windows platforms. In general, this is true of anything under the "plugins" folder. Therefore, if you wanted to make a Metal plugin (implementing the video API), that requires Objective C or Swift, that would be absolutely fine! It wouldn't impact other platforms, and hopefully it could still work with the same build system.

Let me know if you have any questions, I might be able to assist you. :)

- Rodrigo

**Comment by JoelOtter** [comment]
PR not quite here yet - need to do some cleanup - but here's the Halley editor running on the Metal backend. :) 

![Screenshot 2019-04-18 at 15 59 27](https://user-images.githubusercontent.com/2765356/56370628-78043680-61f3-11e9-9871-698830629331.png)

There are a few features I haven't been able to test, such as clipping and texture render target; I'll see if I can write a little demo for them but if there's an open-source Halley example out there that'd be super useful.

Cheers!
Joel
