### ISSUE TITLE
Compiler error with custom yaml-cpp path 

### ISSUE THREAD

**Issue by gurka** [amzeratul/halley#43]
```
[ 83%] Building CXX object src/tools/tools/CMakeFiles/halley-tools.dir/src/assets/asset_importer.cpp.o
In file included from /home/simon/code/halley/src/tools/tools/src/assets/asset_importer.cpp:8:0:
/home/simon/code/halley/src/tools/tools/src/assets/importers/material_importer.h:3:32: fatal error: yaml-cpp/node/node.h: No such file or directory
 #include <yaml-cpp/node/node.h>
                                ^
compilation terminated.
```

Looking at https://github.com/amzeratul/halley/blob/master/src/tools/tools/CMakeLists.txt it looks like `${YAMLCPP_INCLUDE_DIR}` is in the wrong place, in `add_library` instead of in `include_directories`.

**Comment by thoughton** [comment]
Nice one, I just noticed the same problem with `YAMLCPP_INCLUDE_DIR` this evening too!

I tried your fix locally and it works for me. Thanks!

**Comment by guilhermepo2** [comment]
Also just noticed the same problem and fixed it looking at the commit on your pull request.

Thank!
