### ISSUE TITLE
Setup halley with noVNC

### ISSUE THREAD

**Issue by geropl** [amzeratul/halley#48]
This is not a real issue, but more a request for help, I guess. I'm trying to setup halley in a somewhat constrained environment: inside a docker container, with noVNC for displaying.

Specifically I'm using https://gitpod.io, which makes it super easy to tinker on projects like halley (Disclaimer: I'm working for the [company](https://typefox.io) behind Gitpod).

With the help of the patches from [lye](https://github.com/lye) (#37) and [gurka](https://github.com/gurka) (#44) I was able to successfully build and run `./bin/halley-editor tests/entity`:
![image](https://user-images.githubusercontent.com/32448529/53874194-341def00-4002-11e9-923b-9a577f057006.png)

Here is a link to (a copy of) the exact environment I created the screenshot with: [![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/0b9e27fe-72a8-487f-94b2-0f595581f4ff)

Is that the expected output of the test? If yes: Are there any other test "games" I can test the setup with and start playing around with?
Thanks!

**Comment by brandc87** [comment]
That's the correct output for the editor it's scanning asset_src and gen_src for changes, if you look in the halley/src/tests directory there is an entity test (doesn't build for me) but you can see some examples of a render system and animations etc but there is no example game which is what I've been looking for :(

There is the template https://github.com/amzeratul/halley-template but this just has a scene I was hoping @amzeratul maybe had a little project he did for a gamejam or something we could look at.

**Comment by geropl** [comment]
> if you look in the halley/src/tests directory there is an entity test

The output above actually is from the `./bin/halley-editor tests/entity`. From the code I expected to see a rendered scene. Also I could not find a file name "sample_test_world" which I'd expect to contain the scene description.. but I might be totally wrong here.

>  (doesn't build for me)

With the link from [above](https://gitpod.io/#snapshot/0b9e27fe-72a8-487f-94b2-0f595581f4ff) a building/working setup just one registration away. :slightly_smiling_face: 

> There is the template https://github.com/amzeratul/halley-template

Thanks for the hint, missed that one! I will try to set this up.

**Comment by brandc87** [comment]
ah sample_test_world is under halley/src/tests/entity/asset_src/config
It's the world/scene description as you said e.g. what systems are part of the world and timelines.

Thanks i'll check it out :)

**Comment by geropl** [comment]
I managed to replicate the setup for github.com/amzeratul/halley-template: [![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/93f0a347-676d-460b-b20e-48ba51b4213b)

Unfortunately, it only shows a black screen:
![image](https://user-images.githubusercontent.com/32448529/53945530-1adc7780-40c2-11e9-8284-74fa0503b9a7.png)

And I think a I also found the reason:
`Compiling HLSL shaders is not supported on non-Windows platforms.`

**Comment by brandc87** [comment]
There is nothing to draw in the template, it just sets up the window. It uses glsl shaders on the other platforms doesn’t it?

**Comment by geropl** [comment]
> It uses glsl shaders on the other platforms doesn’t it?

Yes, there are GLSL shaders emitted. I was judging by the log output.

> There is nothing to draw in the template,

Ok. That's sad on the one hand, but also very exiting, because - it works! In a browser.

Thank you for your tips and hints! I think I can mark this as closed for now.
