### ISSUE TITLE
Issue building halley-test target

### ISSUE THREAD

**Issue by AnthonyKalaitzis** [amzeratul/halley#52]
I get the following error when trying to build halley through cmake with the following input:
`cmake -DBOOST_ROOT=/home/anthony/bin/boost_1_69_0/boost -DCMAKE_INCLUDE_PATH=/usr/local/include -DCMAKE_LIBRARY_PATH=/usr/local/lib ..`
which gives:
`-- The C compiler identification is GNU 7.3.0`
`-- The CXX compiler identification is GNU 7.3.0`
`-- Check for working C compiler: /usr/bin/cc`
`-- Check for working C compiler: /usr/bin/cc -- works`
`-- Detecting C compiler ABI info`
`-- Detecting C compiler ABI info - done`
`-- Detecting C compile features`
`-- Detecting C compile features - done`
`-- Check for working CXX compiler: /usr/bin/c++`
`-- Check for working CXX compiler: /usr/bin/c++ -- works`
`-- Detecting CXX compiler ABI info`
`-- Detecting CXX compiler ABI info - done`
`-- Detecting CXX compile features`
`-- Detecting CXX compile features - done`
`-- Found SDL2: /usr/include/SDL2 (found version "2.0.8") `
`-- Boost version: 1.69.0`
`-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   `
`-- Found YAMLCPP: /usr/local/include  `
`-- Boost version: 1.69.0`
`-- Found the following Boost libraries:`
`--   system`
`--   filesystem`
`-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "2.8.1") `
`-- Configuring done`
`-- Generating done`
`-- Build files have been written to: /home/anthony/Documents/halley/build`
But when i try to make with `sudo make` i get the error listed in the error.txt file 
[error.txt](https://github.com/amzeratul/halley/files/2988620/error.txt) at 93%. The build target that causes failure is the halley-test-target. Setting this target to 0 allows for a sucessful build

Running: 
- linux mint 19.1
- SDL 2.0.8
- Boost 1.69.0

Any help would be greatly appreciated! I'm quite daft.

**Comment by DrFriday** [comment]
It looks like the test code was written for an older version of halley. I'm going through it right now and can hopefully get the test code updated and running.

**Comment by AnthonyKalaitzis** [comment]
Hey thanks for that! looks like its working a lot better now. Just get a tiny error at the end of the make now:

[ 99%] Building CXX object src/tools/editor/CMakeFiles/halley-editor.dir/src/editor_root_stage.cpp.o
[ 99%] Built target halley-test-audio
[ 99%] Building CXX object src/tools/editor/CMakeFiles/halley-editor.dir/src/halley_editor.cpp.o
CMakeFiles/halley-test-entity.dir/src/test_stage.cpp.o: In function `TestStage::init()':
test_stage.cpp:(.text+0xcd): undefined reference to `Halley::createSystem(Halley::String)'
collect2: error: ld returned 1 exit status
src/tests/entity/CMakeFiles/halley-test-entity.dir/build.make:202: recipe for target '../src/tests/entity/bin/halley-test-entity' failed
make[2]: *** [../src/tests/entity/bin/halley-test-entity] Error 1
CMakeFiles/Makefile2:1230: recipe for target 'src/tests/entity/CMakeFiles/halley-test-entity.dir/all' failed
make[1]: *** [src/tests/entity/CMakeFiles/halley-test-entity.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 99%] Building CXX object src/tools/editor/CMakeFiles/halley-editor.dir/src/preferences.cpp.o
[ 99%] Building CXX object src/tools/editor/CMakeFiles/halley-editor.dir/src/console/console_window.cpp.o
[100%] Building CXX object src/tools/editor/CMakeFiles/halley-editor.dir/src/ui/editor_ui_factory.cpp.o
[100%] Building CXX object src/tools/editor/CMakeFiles/halley-editor.dir/src/ui/taskbar/taskbar.cpp.o
[100%] Linking CXX executable ../../../../bin/halley-editor
[100%] Built target halley-editor
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

``

**Comment by DrFriday** [comment]
Are you using the latest version of halley on the master branch?

**Comment by AnthonyKalaitzis** [comment]
Yes. I've since realised though that building the test network isnt even necessary for a halley-template game so it's not really an issue anymore.
