### ISSUE TITLE
Cannot compile tools on Mac because of Metal

### ISSUE THREAD

**Issue by kencheng** [amzeratul/halley#60]
OS: macOS Mojave 10.14.5

Running cmake yields the error
```
CMake Error at halley/src/tools/editor/CMakeLists.txt:58 (add_dependencies):
  The dependency target "halley-metal" of target "halley-editor" does not
  exist.
```
Metal has been disabled:
https://github.com/amzeratul/halley/blob/master/cmake/HalleyProject.cmake#L146

But it is assumed to be on for Mac systems:
https://github.com/amzeratul/halley/blob/master/src/tools/editor/CMakeLists.txt#L44
https://github.com/amzeratul/halley/blob/master/src/tools/editor/CMakeLists.txt#L54

Guarding by the USE_METAL variable won't work, since the code for Mac requires the Metal libraries to link to:
https://github.com/amzeratul/halley/blob/master/src/tools/editor/src/halley_editor.cpp#L37

**Comment by amzeratul** [comment]
Metal has now been re-enabled!
