### ISSUE TITLE
Build terminates with error

### ISSUE THREAD

**Issue by cangscop** [amzeratul/halley#61]
OS: Arch Linux
Compiling with: cmake/gcc
```
/home/**/Desktop/Sources/halley/src/tests/entity/src/test_stage.cpp: In member function ‘virtual void TestStage::init()’:
/home/**/Desktop/Sources/halley/src/tests/entity/src/test_stage.cpp:8:43: error: ‘createSystem’ was not declared in this scope
    8 |  world = createWorld("sample_test_world", createSystem);
```

**Comment by jdecourval** [comment]
Have you tried simply rebuilding? It looks like you have not run codegen:

> To build a Halley project, you need to run codegen on it first, or it will fail. This is part of the Importing Assets stage. However, if you're building your project and Halley on the same go, and you're building the Halley tools needed for importing the assets, you might have to build first (so the tools build and the game fails), then import, then build again.

https://github.com/amzeratul/halley/wiki/Building

**Comment by cangscop** [comment]
Thanks for the help. I'm closing this issue as my machine recently broke
and I have no way of replicating this.

Il giorno sab 7 set 2019 alle ore 15:50 Jérôme de Courval <
notifications@github.com> ha scritto:
